#+TITLE: Bootstrap User Registration Form
#+SUBTITLE: 2024-03-13 Wed
* What am I doing?
:PROPERTIES:
:ID:       f41e27c6-84b7-4161-ac00-27283764d141
:END:
Outlining the form and specifying the form design for registering as a
Bootstrap user. Participants enrolling in Bootstrap training events are
first added as users and then associated with the training
event. Typically, once a participant registers they can be
automatically enrolled in an event.  This document indicates question
types and further instructions shown to registrants.
* What am I not doing?
- Not creating standard lists for multiple choice.
- Not collecting information about classes
* Distinction between registration and enrollment
- Registration creates a user entity
- Enrollment connects a user to an event
- Users are verified and have access to materials, forum, and mailing list.
* Former Preworkshop Survey
As a reminder the structure of the preworkshop survey was as follows:
** Personal, Identity and Contact
First Name, Last Name, Best email address to reach you, Phone Number
** Professional, Employer
School/Organization Name, District Name, School City, School State, School
Zip,
** Teacher
Grade Level, Teacher License, How many CS classes have you taught
before?,
** Training Event
Which PD are you enrolled in?, Bootstrap Curricula?, I heard
about Bootstrap from...,
** Professional, Affiliated
What is your Desmos username? (if
applicable), If you a member of a professional teachers group (or a
local affiliate) in your discipline (e.g., NCTM for mathematics, CSTA
for computer science), please name it/them here.,
** Personal Demographics
What is your race/ethnic group?, What is your gender?
** Student Demographics
Roughly how many GIRLS do you expect to teach next
year?, Roughly how many BOYS do you expect to teach next year?,
Roughly how many African-American students do you expect to teach next
year?, Roughly how many Hispanic, Latino or Chicano students do you
expect to teach next year?, Roughly how many students have visual or
sensorimotor impairments?, Roughly how many NON-BINARY students
do you expect to teach next year?
** Motivation
Why are you participating in this workshop?,
** Permissions
We routinely take photos, videos, etc during PD in order to
learn and improve future workshops. We may also use these on our
website or social media. Are you uncomfortable with your photo or
video being shared anonymously?,
Grade(s) taught, Subject(s) taught, Subjects 
* Changes
- Consolidates mailing list, teacher material access, and event registration.
- No phone number collection
- Student data collected separately from teacher data
- Logic for whether you are a teacher
- Logic for whether you are an event supervisor
* User Registration Form
** Welcome to the Bootstrap User Registration Form!
*** Description Text
We are thrilled to join you in bringing computing to your
students!

Our goal at Bootstrap is to support teachers over a many years
journey. By registering with Bootstrap you are able to access answer
keys, enroll in trainings, and post on our forum. You'll also receive
invitations and tips from us in your inbox periodically. You can
always opt out of these later.

Most of Bootstrap's users are teachers who work fulltime in
classrooms. However, you might also be an administrator, learning,
coach, or otherwise affiliated with teaching and learning in some
context. Perhaps you're just interested in seeing what this is all
about.

Many of Bootstrap users are also sent to us from districts or other
umbrella organizations that support teachers during training and
throughout the school year. Those partner organizations might contract
with us for additional trainings and on-going suppport and office
hours.

However, you got to Bootstrap we are thrilled to be a part
of your journey!

Click *Next* to continue registering.
** First time registering?
Page break, continue after

Not going to use multiple choice here at first.
- Yes 
  - Continue to enter identification information
- No
  - Enter Bootstrap ID (you do not need to re-register unless there has been a significant change to your contact information or professional affiliation)
  - Continue to update information
*** TODO Create a way to check if you are registered
** Why are you registering with Bootstrap?
- I want to join your mailing list.
- I want to access teacher only materials.
- I am participating or supervising a training event.
** Identity
- Full First Name (as on an official id) (required)
- Nickname or "Call you by" (optional)
- Last Name (as on an official id) (required)
** Contact 
- Professional or school email address (required)
- Google Account Email (the email from which you will access Bootstrap Google resources during the training, if different than above)
- Preferred email for ongoing communication (optional) (if different than above) (can be personal email)
** Event supervisor?
- Supervisor? (are you affiliated with Bootstrap for the purpose of supervising training participants?)
** Is Teacher?
- Teacher? (do you spend the majority of your professional hours supervising students?)
*** Yes
**** School
- School Organization Type (paragraph) (words that describe your organization: public, transfer, performing arts, public charter, independent, independent religiously affiliated, etc. describe your school as you would to a colleague from another school, combining any and all of the above and more.)
- School Community (paragraph) (words to describe the social context of your school: rural, urban, suburban, high poverty, affluent,  combining any and all of the above and more.) 
- School Name
- School District
- School Address
- School Zip Code
- School State
**** Principal
- Principal Name
- Principal Email
- Other Supervisor Role (optional)
- Other Supervisor Name (optional)
- Other Supervisor Email (optional)
**** Teaching
- License (paragraph) (If you are licensed by a State or other organization describe your license here. NY 7-12 Math, etc.)
- Subject (paragraph) (In which subject or department do you typically teach?)
- Grade level (paragraph) (typical grade or grades of students you work with, e.g. 5th, 9th)
- Number of students (number) (how many students do you teach in a given year?)
- Describe students (paragraph) (describe any characteristics that describe your students as a group)
*** No
- Describe your role (describe your professional role and how it relates to teaching and learning, if you are a learning coach or administrator please describe the scope of your work with teachers)
- Participating? (will you be participating in the workshop?)
** Race and Gender
- Permission (may we ask you to identify your race, ethnicity, and gender?)
  - Yes
    - Race (typically not related to cultural background of national origin)
    - Ethnicity (related to cultural background Carribean, African American, White European, Hispanic, Indigenous, Pacific Island, etc.)
    - Gender (transgender male, transgender female, female, male, non-binary)
** Permissions
*** Event participants
- As an event participant you are automatically added to the Bootstrap mailing list to receive tips and tricks, event invitations, and personalized support.
- Opt out select? (you may opt out of receiving addition communication)
  - Tips
  - Event Invitations
  - Coaching
* Form Response
- Welcome to Bootstrap!
