#+TITLE: Participant Data Collection Plan
#+EXPORT_FILE_NAME: ../dataplan.odt
* Purpose
To define the data collected /from/ participants in the Bootstrap
community during the course of enrolling and participating in
facilitated events and implementation support. Additional data
internal to Bootstrap or particular to events, e.g. whether the
participant receives coaching is not included, neither is event
attendance or participation.

Any data group below marked with a *(d)* is considered draft and may be
dropped or included in a later year. Data groups marked with two
dollar signs *($$)* are requirements for enrollment.
* Data Outline
** User
- $$ Name, first and last, alternate first and last name (nickname or name change)
- Race/Ethnicity, gender
- $$ Employer, employer address, role title, date started or years in position
- $$ is-Teacher? (whether or not participant spends majority of working hours supervising students)
  - Yes :: Teaching license, years teaching, computer science experience (anecdotal),
  - No :: Describe education role and/or relationship to teachers and classrooms.
- Professional affiliation
- Classroom tools used (Desmos, Geogebra, code.org, etc.) (d)
- How did you hear about Bootstrap and/or Why are you taking this workshop?
- $$ Supporting partner organization or self pay.
** Class
- Subject, start/end dates, course title, grade level or student age
- School, district, state
- Student demographics (percent_race/ethnicity,percent_gender,percent_disability)
- (d) Context (anecdotal), [remedial/grade-level/advanced, prerequisite]
- (d) Technology in the classroom
  [computer_lab/1-1_laptops/chromebooks], school domain google
  accounts
** Implementation
- Class id (always references a Class, see above)
- Bootstrap lessons used, coaching attended, received support (anecdotal)
- administrative support (anecdotal),
** Skills
Skills are currently assessed in aggregate with anonymous pre and post diagnostics administered during a training.
# Diagnostic is a misnomer: we don't use this data to craft instruction. Rather, we use pre and post data to investigate growth in knowledge at the end of the training event.

Individual skills assessment data aligned to a curriculum specific skills framework wait for future planning.
